# Generated by Django 4.2.4 on 2024-04-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_addfriend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addfriend',
        ),
    ]
